/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.deploymanager.gui;

import com.deploymanager.controller.MainController;
import com.deploymanager.controller.TestModel;
import com.swingmvp.Presenter;
import com.swingmvp.View;
import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author marek
 */
public class MainView extends javax.swing.JFrame implements View {
    
    private MainController _controller;

    /**
     * Creates new form MainView
     */
    public MainView(Presenter presenter) {
        _controller = (MainController) presenter;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        valueDisplay = new javax.swing.JTextField();
        increment = new javax.swing.JButton();
        openModalWIndow = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Wartość to:");

        increment.setText("Inkrementuj");
        increment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incrementActionPerformed(evt);
            }
        });

        openModalWIndow.setText("Otwórz okno modalne");
        openModalWIndow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openModalWIndowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(openModalWIndow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(increment, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                        .addComponent(valueDisplay)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(valueDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(increment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(openModalWIndow)
                .addContainerGap(193, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setController(MainController controller) {
        _controller = controller;
    }
    
    private void incrementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incrementActionPerformed
        _controller.incrementLabelValue();
    }//GEN-LAST:event_incrementActionPerformed

    private void openModalWIndowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openModalWIndowActionPerformed
        _controller.showModalWindow("Test");
    }//GEN-LAST:event_openModalWIndowActionPerformed

    @Override
    public void update(Observable o, Object arg) {
        TestModel model = (TestModel) o;
        valueDisplay.setText(model.getValue().toString());
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton increment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton openModalWIndow;
    private javax.swing.JTextField valueDisplay;
    // End of variables declaration//GEN-END:variables


    @Override
    public void observePresenterModel() {
        
    }

    @Override
    public void displaySubView(View subView) {
        
    }
}
